### PR TITLE
fix: typo in example in README.md

### PR DESCRIPTION
**Pull request by Alvish0407**

### CODE REVIEW

**Review by loicgeek — COMMENTED** [review]
Hello @Alvish0407  have you tested properly?

**Comment by Alvish0407** [comment]
Hello @loicgeek,
Yes, I encountered that problem so I checked underlying code and tried replacing params. It worked.

**Comment by Alvish0407** [comment]
Check this 

```dart
typedef OnCropDataCallback = void Function(
  int dx,
  int dy,
  int w,
  int h,
);
```

**Comment by loicgeek** [comment]
Okay, were you on landscape mode?

**Comment by Alvish0407** [comment]
No. In Portrait.

**Comment by Alvish0407** [comment]
```dart
CustomRatioCameraPreview(
  expectedRatio: 1.586,
  cameraController: documentCameraController!,
  onCropData: (dx, dy, w, h) {
    print(dx);
    print(dy);
    print(h);
    print(w);
  },
),
```

**Comment by loicgeek** [comment]
@Alvish0407  can you make the test on landscape also please

**Comment by Alvish0407** [comment]
Doing same.

**Comment by loicgeek** [comment]
Oh okay, it is just a typo in the sample, yes got it, closing now

**Comment by Alvish0407** [comment]
@loicgeek Thanks for the package.
I had been finding solution to crop camera preview for 2 days. All solutions I found were squeezing the preview. But yours worked.

**Comment by loicgeek** [comment]
I am happy it solved your requirement

**Comment by loicgeek** [comment]
can you make me a favour an test the latest on https://github.com/loicgeek/custom_ratio_camera, since you currently have a project in hands

**Comment by Alvish0407** [comment]
Sure.

**Comment by Alvish0407** [comment]
@loicgeek 
```yaml
custom_ratio_camera:
  git:
    url: https://github.com/loicgeek/custom_ratio_camera
    ref: main
 ```
 
 Working Fine.

**Comment by loicgeek** [comment]
Okay thank you, going to release it now

**Pull request merged**
